# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/HLS_Projects/iris_hls/iris_hls_vivado/iris_hls_vivado.srcs/sources_1/bd/design_1/ip/design_1_iris_module_0_1/design_1_iris_module_0_1.xci
# IP: The module: 'design_1_iris_module_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/HLS_Projects/iris_hls/iris_hls_vivado/iris_hls_vivado.gen/sources_1/bd/design_1/ip/design_1_iris_module_0_1/constraints/iris_module_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_iris_module_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/HLS_Projects/iris_hls/iris_hls_vivado/iris_hls_vivado.srcs/sources_1/bd/design_1/ip/design_1_iris_module_0_1/design_1_iris_module_0_1.xci
# IP: The module: 'design_1_iris_module_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/HLS_Projects/iris_hls/iris_hls_vivado/iris_hls_vivado.gen/sources_1/bd/design_1/ip/design_1_iris_module_0_1/constraints/iris_module_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_iris_module_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
