# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/project/23th-project/iris_hls/iris_hls_vivado/iris_hls_vivado.srcs/sources_1/bd/design_2/ip/design_2_processing_system7_0_0/design_2_processing_system7_0_0.xci
# IP: The module: 'design_2_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/project/23th-project/iris_hls/iris_hls_vivado/iris_hls_vivado.gen/sources_1/bd/design_2/ip/design_2_processing_system7_0_0/design_2_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/project/23th-project/iris_hls/iris_hls_vivado/iris_hls_vivado.srcs/sources_1/bd/design_2/ip/design_2_processing_system7_0_0/design_2_processing_system7_0_0.xci
# IP: The module: 'design_2_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/project/23th-project/iris_hls/iris_hls_vivado/iris_hls_vivado.gen/sources_1/bd/design_2/ip/design_2_processing_system7_0_0/design_2_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
